### ISSUE TITLE
feat: integrating yapf into the armada

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#102]
We would like to add the yapf tool into armada in order to test and format
**Is this a bug report or feature request?** (choose one): feat

**Python Version** (output of `python --version`): 2.7

**Development or Deployment Environment?**: Develop

**Release Tag or Master**: Master

**Expected Behavior**: 
- [ ] create a tox command to format the current source code
- [ ] create a tox command to validate that the code has been correctly formatted to be used for testing.

**Any Additional Comments**:

https://github.com/google/yapf

**Comment by MarshM** [comment]
Closing as unnecessary, yapf is currently not needed.  Feel free to reopen in the future, if anyone wants this.
