### ISSUE TITLE
bug: Armada cannot run on MacOS

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/armada#11]
**Is this a bug report or feature request?** (choose one):

**Python Version** (output of `python --version`): 2.7.9

**Development or Deployment Environment?**: MacOS

**Release Tag or Master**: master

**Expected Behavior**: Armada functions as per README.md

**What Actually Happened**: Exception

**How to Reproduce the Issue** (as minimally as possible):

Follow README steps.

The log mechanisms leverage `/dev/log` which do not exist on MacOS.

The following "hack" was necessary to get it functioning, however the proper solution needs to work for both Linux and MacOS, instead of the simple swap below.

There were also requirements.txt processing issues that behaved differently on MacOS.  The pygit2 library needed to be at version 0.25 to match the libgit version on MacOS.  The kubernetes version needed to be explicitly set as auto discovering the latest version--likely due to the unique version scheme of these packages--was failing for a 2.7.9 virtual environment on MacOS.

```
diff --git a/armada/logutil.py b/armada/logutil.py
index abe1422..e9a509e 100644
--- a/armada/logutil.py
+++ b/armada/logutil.py
@@ -11,7 +11,7 @@ LOG_DATE = '%m-%d %H:%M'
 def setup_logging(args):
     level = logging.DEBUG if args.debug else logging.INFO
     logging.basicConfig(level=level, format=LOG_FORMAT, date_fmt=LOG_DATE)
-    handler = SysLogHandler(address='/dev/log')
+    handler = SysLogHandler(address='/var/run/syslog')
     syslog_formatter = logging.Formatter('%(name)s: %(levelname)s %(message)s')
     handler.setFormatter(syslog_formatter)
-    LOG.addHandler(handler)
\ No newline at end of file
+    LOG.addHandler(handler)
diff --git a/requirements.txt b/requirements.txt
index 127ba24..43b6e7f 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,5 +3,5 @@ grpc
 pyyaml
 grpcio
 grpcio-tools
-kubernetes
-pygit2==0.24.0
+kubernetes==1.0.0b1
+pygit2==0.25.0
```

**Comment by gardlt** [comment]
I know that in OSX you will have version problems with the pygit2 and your libgit2 version dont match. i know if you do a `brew install libgit2` it will only install latest stable == 0.25.0 so the `pip install` will fail since we require pygit2==0.24

**Comment by v1k0d3n** [comment]
i have similar issues in Ubuntu 16.10 as well. i'll paste these issues in later today when i have a moment, so we can track these bugs in this single issue.

**Comment by gardlt** [comment]
There are kinda multiple issues in here. So i broke it up:
#19
#16

**Comment by gardlt** [comment]
Closing this issue since it has been broken up.
