### ISSUE TITLE
armada doesn't ignore files listed in .helmignore

### ISSUE THREAD

**Issue by alop** [att-comdev/armada#13]
**Is this a bug report or feature request?** (choose one):
bug report

**Python Version** (output of `python --version`):
 python --version
Python 2.7.12

**Development or Deployment Environment?**:
development
**Release Tag or Master**:
master

**Expected Behavior**:
Files listed in .helmignore would be ignored

**What Actually Happened**:
armada errored out due to unterminated quote in an rst file that should be ignored

**How to Reproduce the Issue** (as minimally as possible):
point armada at kolla-kubernetes/helm/kolla-common

**Any Additional Comments**:

**Comment by alanmeadows** [comment]
@alop This is a good find.  @gardlt Can you take this?

**Comment by gardlt** [comment]
hey @alop can you please provide your armada.yaml?

**Comment by gardlt** [comment]
Unable to reproduce issue, close for now.
