### ISSUE TITLE
feat:  Convert armada CLI into Click

### ISSUE THREAD

**Issue by g0r1v3r4** [att-comdev/armada#138]
**Is this a bug report or feature request?** (choose one):

**Python Version** (output of `python --version`): 2.7

**Development or Deployment Environment?**:

**Release Tag or Master**: master

**Expected Behavior**:
Refactor the armada CLI to use the Click framework

All functionally must be supported successfully in the new format

Main reason
- To avoid Cliff conflicting dependencies

**Comment by gardlt** [comment]
we have update cli to click
