### ISSUE TITLE
feat: determine a release schedule and roadmap for armada

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#14]
**Any Additional Comments**:

we need to start forming a release schedule/roadmap with defined features in armada. priority one is resolving issues that prevent people from using armada. this is before any of the golang conversion should occur.

**Comment by gardlt** [comment]
Roadmap: 

v0.1.0 (March Release)
- feat: lint - make application pep8 compliant
- feat: CI - provide a form of testing pipeline
- feat: container - create docker file to run application service
- docs: provide armada yamls for a: 
	- keystone, memcache, rabbitmq, database
	- stable/kubernetes chart i.e. wordpress

v0.2.0 (April Release)
- feat: check that tiller is alive 
- feat: armada can pull repos via ssh instead from an anonymous state
- feat: delete - charts that match a armada yaml
- feat: upgrade - deployed charts need to be upgraded 
	- remove the old jobs
	- re run the new jobs. 
- feat: deploy - charts using a armada yaml
- docs: update any common to helm-toolkit
- docs: armada - troubleshoot - guide of known or common issues with tool

v0.3.0 (May Release)
- feat: services - execute armada lib via API calls
- feat: configure - manage Armada via a configuration file
- feat: deploy tiller using helm init if it does not exist

Future Enhancements:
- deploy one chart in several kubernetes clusters
- helm - armada - integrations

**Comment by gardlt** [comment]
this is the rope of issues and features that we should be seeing int he next milestone. @v1k0d3n @alanmeadows i would like your input and i will make sure to do an official publish.
