### ISSUE TITLE
Unprivileged armada breaks promenade integration

### ISSUE THREAD

**Issue by sh8121att** [att-comdev/armada#141]
**Is this a bug report or feature request?** (choose one):
BUG

**Python Version** (output of `python --version`): 3.5

**Development or Deployment Environment?**: Deployment

**Release Tag or Master**: Master

**Expected Behavior**: Promenade integration assumes it can provide the Armada container a .kube/config file to use. The change to running as 'armada' breaks this as the armada account does not have write access to its own home directory

**What Actually Happened**: 
Permission denied error attempting to run
'mkdir /armada/.kube/config'

**How to Reproduce the Issue** (as minimally as possible):
Run promenade genesis

**Any Additional Comments**:

**Comment by gardlt** [comment]
I believe this will resolve this issue #142
