### ISSUE TITLE
feat: source - change git dependecy to gitpython

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#150]
**Is this a bug report or feature request?** (choose one): feat

**Python Version** (output of `python --version`): 2.7

**Expected Behavior**:

We are currently using the ligit2/pygit2 lib to clone our reposes for the `source` type `git`. We would move to a lightweight lib that can possibly achieve the same or more goals. 

https://github.com/gitpython-developers/GitPython

**Comment by theyer** [comment]
Added in commit 84
