### ISSUE TITLE
Armada AIO ReleaseInstallException

### ISSUE THREAD

**Issue by EckyYakov** [att-comdev/armada#158]
**Is this a bug report or feature request?** (choose one): Bug

**Python Version** (output of `python --version`):
Python 2.7.12
**Development or Deployment Environment?**:
Development
**Release Tag or Master**:
Master
**Expected Behavior**:
releasearmada-mariadb should install successfully
**What Actually Happened**:
ERROR armada [-] Failed to install releasearmada-mariadb.: ReleaseInstallException: Failed to install releasearmada-mariadb.
**How to Reproduce the Issue** (as minimally as possible):
Set up openstack helm environment using the all in one.
run:
armada apply /examples/armada-aio.yaml
**Any Additional Comments**:
Talked with Alex on this one, seems like it is falsely detecting a change in the chart, trying to update it, and failling because there is nothing to update.
Tiller was up and running
Everything openstack helm was up and successfully deployed.

**Comment by Roadrunner2058** [comment]
@EckyYakov Is this issue still applicable?  Are you still experiencing issues?

**Comment by EckyYakov** [comment]
@Roadrunner2058 I have not looked at it for a long while. Not sure if the issue still exists.

**Comment by Roadrunner2058** [comment]
We're working through all open issues, when you have time please let me know if this should still be open.

**Comment by EckyYakov** [comment]
I'd say close it. Cheers.

**Comment by Roadrunner2058** [comment]
Thanks! o/
