### ISSUE TITLE
Armada as a plugin

### ISSUE THREAD

**Issue by EckyYakov** [att-comdev/armada#160]
**Is this a bug report or feature request?** (choose one): Feature request

**Python Version** (output of `python --version`):

**Development or Deployment Environment?**:

**Release Tag or Master**:

**Expected Behavior**:

**What Actually Happened**:

**How to Reproduce the Issue** (as minimally as possible):

**Any Additional Comments**:

**Comment by gardlt** [comment]
This Issue has been resolved in #164
