### ISSUE TITLE
feat: armada plugin to fleet plugin

### ISSUE THREAD

**Issue by EckyYakov** [att-comdev/armada#164]
**Is this a bug report or feature request?** (choose one): feature request

**Python Version** (output of `python --version`):

**Development or Deployment Environment?**:

**Release Tag or Master**:

**Expected Behavior**:

**What Actually Happened**:

**How to Reproduce the Issue** (as minimally as possible):

**Any Additional Comments**:

**Comment by gardlt** [comment]
This has been completed, will close issue.
