### ISSUE TITLE
helm plugin instructions are incorrect

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#166]
**Is this a bug report or feature request?** (choose one):

**Python Version** (output of `python --version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: master

**Expected Behavior**: Instructions are not correct for installing the helm plugin.

**What Actually Happened**: Plugin doesn't work as expected or advertised.

**How to Reproduce the Issue** (as minimally as possible): follow instructions that are included in master.

**Any Additional Comments**:

The actual instructions should be:

```
helm plugin install https://github.com/att-comdev/armada.git

### Then you can run the following:
sudo helm armada tiller install
Creating an Armada container...
Unable to find image 'quay.io/attcomdev/armada:latest' locally
latest: Pulling from attcomdev/armada
50513f4bae65: Pull complete
1114e9d04b40: Pull complete
f96d67146fbf: Pull complete
0a989a282ba0: Pull complete
4416a7a5b830: Pull complete
a3ed95caeb02: Pull complete
81ecf8d19053: Pull complete
7caa09b9a66a: Pull complete
Digest: sha256:a5d80de49cd8a9c548ae4c9629026f6effaf25efc487329976d7b2b6bc38ddfd
Status: Downloaded newer image for quay.io/attcomdev/armada:latest
70a417c0f866f40a7d9cd2b408627709437f0037c68f586f8a689c8e52872035
usage: armada tiller [-h] [--status] [--releases]
armada tiller: error: unrecognized arguments: install
Destroying armada container...
...container destroyed
```

Instructions just need to change slightly.

**Comment by gardlt** [comment]
@EckyYakov would you like to take this?

**Comment by EckyYakov** [comment]
Yeah i got this @gardlt
