### ISSUE TITLE
docs: armada - troubleshoot - guide of known or common issues with tool

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#17]
With the various unexpected problems one could face, we need to create a `troubleshooting.rst` to cover scenarios which document some solutions/fixes/workarounds. An example is the pygit2 library.

Expect:
- [ ] in the docs sub dir create a `troubleshooting.rst` to cover these scenarios

Known Troubleshooting:
ALL:
- install of the google.protobuf, to where you python packages are install and make sure the google root dir has a `__init__.py` else python will not recognize it as a package
OS X:
- when using the python Kubenetes lib your python ssl lib should be >=1.0.0

**Comment by alanmeadows** [comment]
Another possibility to consider also is to separate pygit2 from requirements.txt and instruct its installation separately based on the library version the user has on the system (with examples of how to retrieve this for mac, redhat, debian).

**Comment by gardlt** [comment]
I agree. The pygit2/libgit2 components need to be documented or scripted because it's a big hurdle to get the environment running. It took some time setting this up on OS X and Ubuntu. 

SIDE NOTE: depending on the environment you cannot install certain versions of pygit2. i.e. ubuntu 16.04 i can only install pygit2==0.25.0. The reason that travis CI works in installing libgit/pygit2==0.24.0 is because the default vm is Ubuntu 1404 Trusty.

**Comment by v1k0d3n** [comment]
@gardlt should we use docker to build in a 16.04 container to overcome that hurdle? if we use this as our path forward, then we can also do CI for CentOS as well.

**Comment by v1k0d3n** [comment]
man, while i understand Travis' position on this to an extent; this reaction somewhat worries me a little: https://github.com/travis-ci/travis-ci/issues/5821

**Comment by gardlt** [comment]
Created separate issue for a scripted install of the library #19

**Comment by gardlt** [comment]
done in #52
