### ISSUE TITLE
feat: framework - using a cmd library/framework to handle app execution

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#18]
As developers, i want use libraries like [cliff](https://docs.openstack.org/developer/cliff/), [click](http://click.pocoo.org/5/), ect. This will allow for a standardization of how to create future command and will help improve flag handling.

**Comment by alanmeadows** [comment]
Although this is likely a separate feature from this, this feature should also factor into the need to have there be a REST API portion (with auth) of armada, to allow it to be used in complex workflows that don't have the ability to run it locally.

In a python sense, something very similar to openstack practices of CLI calling API.  Also very similar to helm itself except would not suggest another layer of gRPC, but a simple REST framework.  I would keep an eye on what is being done for github.com/att-comdev/drydock as it is leveraging this same model for MaaS using pecan complete with plugins and auth.

**Comment by gardlt** [comment]
Correct when adding this feature we will need to follow something similar to the openstack cli practices or fuels. in order to utilize the armada lib not just as a cli tool, but a library, that just so happens to have a CLI. good add @alanmeadows.

**Comment by gardlt** [comment]
done in #52
