### ISSUE TITLE
Armada apply exception thrown while deploying  OSH , specifically mariadb chart, although its working.

### ISSUE THREAD

**Issue by jezogwza** [att-comdev/armada#182]
**Is this a bug report or feature request?** (choose one):
**BUG**

**Python Version** (output of `python --version`):

**Development or Deployment Environment?**:
Several environments. Mainly Dev Lab's.

**Release Tag or Master**:

**Expected Behavior**:
Clearly I would like Armada apply to run its course and successful deploy without the need for the retry in cases where there isn't an actual error.

**What Actually Happened**:
When deploying OSH with Armada, it consistently will throw an error during the MariaDB deployment. Even though MariaDb actually successfully deploys.  Basically  deploying OSH with Armada is almost always : 1) Apply OSH yaml. It will claim to fail because of a Maria DB error 2) We watch MariaDB pods until they are up 3) Appy OSH again and then it will complete the rest just fine.
The error during the MariaDB deployment is not a timeout. We have tried increasing the timeout value in the Chart . Seems to be some miscommunication between Armada and Tiller.

Don't have the example exception at the moment will paste one during the next time we deploy.

**How to Reproduce the Issue** (as minimally as possible):
Deploy OSH-NEWTON using Armada apply.

**Any Additional Comments**:

**Comment by gardlt** [comment]
yes, we are trying to solve this issue. mark has pointed out that tiller is honoring the timeout but our grpc calls are not we are extending the timeouts to see if this solves the issue. https://review.gerrithub.io/#/c/390489/
