### ISSUE TITLE
bug: charts require toplevel key 'timeout'

### ISSUE THREAD

**Issue by sh8121att** [att-comdev/armada#186]
BUG

**Python Version** (output of `python --version`): Whatever your Dockerfile uses

**Development or Deployment Environment?**: Development

**Release Tag or Master**: Master (image hash 2056a914639f)

**Expected Behavior**: Removing the top-level chart key `timeout` and using only `wait.timeout` would successfully deploy a Chart.

**What Actually Happened**: Docs specify that the top-level key `timeout` in a Chart is deprecated, but if it is missing Armada throws an exception and does not attempt to deploy the chart

**How to Reproduce the Issue** (as minimally as possible): Remove `timeout` from a Armada chart and attempt to deploy it.

**Comment by MarshM** [comment]
This should be closed and working as of [this commit](https://github.com/att-comdev/armada/commit/efd42dfab25eb96dbe48a55d3d2190f25c63f6ba).  Top-level timeout key will be deprecated gracefully in an upcoming version.

Please reopen if there are further issues.
