### ISSUE TITLE
ci: add Travis-CI to armada repo

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#2]
add simple CI and potential unit test to this repo:

* add `.travis.yml` to the repo
* use instructions included in main README.md to get unit test/gating in place

@gardlt is this something you would want to pick up? seems to be right in your wheelhouse. if so...i can assign it to you.

**Comment by gardlt** [comment]
@v1k0d3n i can pick this up.

**Comment by v1k0d3n** [comment]
thanks again @gardlt

**Comment by gardlt** [comment]
- [ ] create .travis file
- [ ] run simple tasks

**Comment by v1k0d3n** [comment]
fixed in #4
