### ISSUE TITLE
feat: create armada docker container for stability

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#20]
**Python Version** (output of `python --version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: N/A

**Expected Behavior**: N/A

**What Actually Happened**: N/A

**How to Reproduce the Issue** (as minimally as possible): N/A

**Any Additional Comments**: N/A

This is a **feature**:
I want a Dockerfile/image for Armada that can be referenced in documentation. I also want to find a reason for *not* just using this stable container, as I personally have run into a lot of issues running Armada directly on various hosts (OSX and Ubuntu 16.10). Maybe this is the *only* way to run Armada, but if that is our goal we need to test it thoroughly.

- [x] create an Armada Docker container based on Ubuntu 16.04
- [x] test functionality
- [x] document in the Armada readme

**Comment by gardlt** [comment]
https://github.com/att-comdev/dockerfiles/pull/74

**Comment by v1k0d3n** [comment]
@gardlt hey, what is the current status with this Dockerfile effort? are you working on this, or is there anything I can help with?

**Comment by gardlt** [comment]
this has been completed
