### ISSUE TITLE
feat: add new repo items

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/armada#3]
we need the following items included in this repo:

* OWNERS
* templates for issues/pull requests

we want to get this repo in line with openstack-helm and the other repositories for consistency. @gardlt this one too?

**Comment by gardlt** [comment]
@v1k0d3n i can pick this up.

**Comment by v1k0d3n** [comment]
awesome! thanks @gardlt

**Comment by gardlt** [comment]
- [x] github issue standards
- [x] owners file

**Comment by v1k0d3n** [comment]
fixed in #5 and #4
