### ISSUE TITLE
feat: logging - imporve format and methond to log armada

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#53]
**Is this a bug report or feature request?** (choose one): feat

**Python Version** (output of `python --version`): 2.7

The logging for the armada tool needs to be better structure and configurable via a logging.cfg

* if logging file not present default the loggging
* if logging is present, then override the logging format as provided
* we need to make sure that logging can be displayed via docker logs
* provide proper levels of logging

**Comment by intlabs** [comment]
perhaps using oslo for this and the config makes sense?

**Comment by gardlt** [comment]
@intlabs yep, that is what we are thinking of doing. we kinda want to try to reuse the oslo tools as much as possible since they are generic enough.

**Comment by drewwalters96** [comment]
@gardlt I can implement this feature
