### ISSUE TITLE
bug: missing return or pass 

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#6]
**Is this a bug report or feature request?** (choose one): bug

**Python Version** (output of `python --version`): 2.7

**Development or Deployment Environment?**: virtualenv

**Release Tag or Master**: master

**Expected Behavior**:
* return or pass at the end 
-or-
* remove function

**What Actually Happened**:
missing return/pass keyword

**How to Reproduce the Issue** (as minimally as possible):
1. go to https://github.com/att-comdev/armada/blob/master/armada/tiller.py#L96

**Any Additional Comments**:

**Comment by alanmeadows** [comment]
@gardlt Agreed, this method should simply be removed, a vestige missed during initial commit.  A good find.
