### ISSUE TITLE
Missing pre field exception lacking detail

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/armada#67]
When using a manifest missing the _pre_ field entirely (and presumably post), the error message to the user is not intuitive.  Presumably this (and other YAML validation) could be caught pre-flight, before processing the charts.  

Also, can't these be optional? I may have upgrade options to pass to tiller but no request for pre and post k8s actions.

```

# armada apply mitaka.yaml 
06-16 14:29 armada.handlers.armada INFO     Performing Checking Pre Flight Tasks
06-16 14:29 armada.handlers.chartbuilder INFO     Building dependency chart helm-toolkit for release mariadb
06-16 14:29 armada.handlers.armada INFO     Upgrading release mariadb
06-16 14:29 armada       ERROR    'pre'
```

**Comment by gardlt** [comment]
The issue is how we do our checking, the getattr() is still passing the pre keyword from the aramda file. we have a hotfix on the way
