### ISSUE TITLE
bug: fix linting issues for pep8 complient

### ISSUE THREAD

**Issue by gardlt** [att-comdev/armada#7]
**Is this a bug report or feature request?** (choose one): bug

**Python Version** (output of `python --version`): 2.7

**Development or Deployment Environment?**: virtualenv

**Release Tag or Master**: master

**Expected Behavior**: 
Expect to be pep8 compliant 

**What Actually Happened**:
we are failing linting test

**How to Reproduce the Issue** (as minimally as possible):
1. pip install -r test-requirements.txt
2. flake8

**Any Additional Comments**:

**Comment by alanmeadows** [comment]
Thanks @gardlt. This would be an excellent cleanup to have this be pep8 compliant.
