### ISSUE TITLE
[Feat] Cmd - Implement Openstack Cookiecutter 

### ISSUE THREAD

**Issue by drewwalters96** [att-comdev/armada#81]
**Is this a bug report or feature request?** (choose one): feature

**Python Version** (output of `python --version`): 2.7

**Development or Deployment Environment?**: All

**Release Tag or Master**: 0.4

**Expected Behavior**: Leverage the Oslo config library alongside the cookiecutter scaffolding tool from Openstack

**Any Additional Comments**: @gardlt 

https://github.com/openstack-dev/cookiecutter

**Comment by g0r1v3r4** [comment]
@gardlt what is the motivation of using the OpenStack cookicutter, especially, if Armada is not meant to move to OpenStack. If we want certain enhanced project configurations, I believe they can achieved without the cookicutter since it's mostly meant for new projects.

**Comment by v1k0d3n** [comment]
please don't move armada to openstack. there is a high level of interest in Armada being part of Helm or Kubernetes, and in fact we've sold it to the community as such.

**Comment by gardlt** [comment]
we are not going to persue this anymore.
